export default {
    GET_PROJECT: 'GET_PROJECT',
    SET_PROJECT: 'SET_PROJECT',
    GET_PROJECTS: 'GET_PROJECTS',
    SET_PROJECTS: 'SET_PROJECTS',
    DELETE_PROJECT: 'DELETE_PROJECT',
    SET_DELETE_PROJECT: 'SET_DELETE_PROJECT',
    CREATE_PROJECT: 'CREATE_PROJECT',
    ADD_PROJECT: 'ADD_PROJECT',
    UPDATE_PROJECT: 'UPDATE_PROJECT',
    SET_UPDATE_PROJECT: 'SET_UPDATE_PROJECT',
}